[package]
name = "rust-neuron"
version = "0.1.0"
authors = ["shunt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot ="0.0.32"
rand = "0.7.2"
rayon = "1.2.1"
